#!/usr/bin/env node
// Generate psl_data.js from the publicsuffix.org list.

const fs = require("fs");
const https = require("https");
const path = require("path");

const URL = "https://publicsuffix.org/list/public_suffix_list.dat";
const OUT = path.join(__dirname, "..", "psl_data.js");

function download(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, (res) => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          resolve(download(new URL(res.headers.location, url).href));
          return;
        }
        if (res.statusCode !== 200) {
          reject(new Error(`${url}: HTTP ${res.statusCode}`));
          return;
        }
        let body = "";
        res.setEncoding("utf8");
        res.on("data", (chunk) => {
          body += chunk;
        });
        res.on("end", () => resolve(body));
      })
      .on("error", reject);
  });
}

function parse(text) {
  const rules = [];
  const wildcards = [];
  const exceptions = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("//")) continue;
    const normalized = line.toLowerCase();
    if (normalized.startsWith("!")) {
      exceptions.push(normalized.slice(1));
    } else if (normalized.startsWith("*.")) {
      wildcards.push(normalized.slice(2));
    } else {
      rules.push(normalized);
    }
  }
  return {
    rules: [...new Set(rules)].sort(),
    wildcards: [...new Set(wildcards)].sort(),
    exceptions: [...new Set(exceptions)].sort()
  };
}

async function main() {
  const text = await download(URL);
  const data = parse(text);
  const output =
    "// Generated by tools/build_psl.js from publicsuffix.org. Do not edit by hand.\n" +
    "const PUBLIC_SUFFIX_RULES = " + JSON.stringify(data.rules) + ";\n" +
    "const PUBLIC_SUFFIX_WILDCARDS = " + JSON.stringify(data.wildcards) + ";\n" +
    "const PUBLIC_SUFFIX_EXCEPTIONS = " + JSON.stringify(data.exceptions) + ";\n";
  fs.writeFileSync(OUT, output);
  console.log(
    `Wrote psl_data.js (${data.rules.length} rules, ${data.wildcards.length} wildcards, ${data.exceptions.length} exceptions)`
  );
}

main().catch((err) => {
  console.error("PSL build failed:", err.message || err);
  process.exit(1);
});
