// QuietBrowse - filter list build script
// Downloads EasyList + EasyPrivacy and compiles them (via ../filter_compiler.js) into:
//   easylist_rules.json  - declarativeNetRequest network rules
//   cosmetic_filters.js  - generic element-hiding selectors + bundled procedural rules
//   cosmetic_sites.json  - per-site hide/unhide selector maps
//
// Usage:  node tools/build_filters.js [easylist.txt easyprivacy.txt]
// (Pass local files to skip the download.)

const https = require("https");
const fs = require("fs");
const path = require("path");
const { compileFilters } = require("../filter_compiler.js");

const LISTS = [
  "https://easylist.to/easylist/easylist.txt",
  "https://easylist.to/easylist/easyprivacy.txt"
];

const OUT_DIR = path.join(__dirname, "..");

// Must match background.js: allow rules 1.., block rules 50000..
const BLOCK_ID_START = 50000;

function download(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        return resolve(download(new URL(res.headers.location, url).href));
      }
      if (res.statusCode !== 200) {
        return reject(new Error(`${url}: HTTP ${res.statusCode}`));
      }
      let data = "";
      res.on("data", (c) => (data += c));
      res.on("end", () => resolve(data));
    }).on("error", reject);
  });
}

async function main() {
  const localFiles = process.argv.slice(2);
  const texts = [];
  if (localFiles.length > 0) {
    console.log("Reading local filter lists...");
    for (const f of localFiles) {
      const text = fs.readFileSync(f, "utf8");
      console.log(`  ${f} (${(text.length / 1e6).toFixed(1)} MB)`);
      texts.push(text);
    }
  } else {
    console.log("Downloading filter lists...");
    for (const url of LISTS) {
      const text = await download(url);
      console.log(`  ${url} (${(text.length / 1e6).toFixed(1)} MB)`);
      texts.push(text);
    }
  }

  const c = compileFilters(texts);

  const allowRules = c.allowRules.map((r, i) => ({ ...r, id: i + 1 }));
  const blockRules = c.blockRules.map((r, i) => ({ ...r, id: BLOCK_ID_START + i }));
  fs.writeFileSync(
    path.join(OUT_DIR, "easylist_rules.json"),
    JSON.stringify([...allowRules, ...blockRules])
  );

  // Build bundled procedural rules: site-specific first (up to 2000 total)
  const MAX_PROC = 2000;
  const procFlat = [];
  for (const [domain, rules] of Object.entries(c.proceduralRules || {})) {
    if (!domain || procFlat.length >= MAX_PROC) break;
    for (const r of rules) {
      if (procFlat.length >= MAX_PROC) break;
      procFlat.push({ ...r, domains: [domain] });
    }
  }
  for (const r of (c.proceduralRules[""] || [])) {
    if (procFlat.length >= MAX_PROC) break;
    procFlat.push({ ...r, domains: [] });
  }

  fs.writeFileSync(
    path.join(OUT_DIR, "cosmetic_filters.js"),
    "// Generated by tools/build_filters.js - generic element-hiding selectors\n" +
      "// from EasyList. Do not edit by hand; re-run the build script instead.\n" +
      "const GENERIC_HIDE_SELECTORS = " +
      JSON.stringify(c.genericSelectors) +
      ";\n" +
      "const BUNDLED_PROCEDURAL_RULES = " +
      JSON.stringify(procFlat) +
      ";\n"
  );

  fs.writeFileSync(
    path.join(OUT_DIR, "cosmetic_sites.json"),
    JSON.stringify({ hide: c.siteHide, unhide: c.siteUnhide })
  );

  const s = c.stats;
  console.log(`\nCompiled:`);
  console.log(`  ${s.domainCount} blocked domains (merged into ${s.groupedRules} grouped rules)`);
  console.log(`  ${s.patternRules} pattern block rules`);
  console.log(`  ${s.allowRules} exception rules`);
  console.log(`  ${s.genericSelectors} generic cosmetic selectors`);
  console.log(`  ${s.siteHideDomains} domains with site-specific cosmetics`);
  console.log(`  ${s.siteUnhideDomains} domains with cosmetic exceptions`);
  console.log(`  ${s.proceduralRules} procedural rules (has-text/upward/remove) — ${procFlat.length} bundled`);
  console.log(`  ${s.skipped} unsupported rules skipped`);
  console.log(`\nWrote easylist_rules.json, cosmetic_filters.js, cosmetic_sites.json`);
  console.log("Reload the extension in chrome://extensions to apply.");
}

main().catch((err) => {
  console.error("Build failed:", err.message || err);
  process.exit(1);
});
